version: '2'
services:
  named:
    image: dirmich/nameserver

    container_name: named

    network_mode: host

    volumes:
      - ./nameserver/named.conf:/etc/bind/named.conf
      - ./nameserver/zones:/var/lib/bind

    ports:
      - "53:53/tcp"
      - "53:53/udp"
